### ISSUE TITLE
Sticky session support

### ISSUE THREAD

**Issue by LeonidEfremov** [webserver-llc/angie#21]
It is possible to stick session between client and backend server via cookie?

**Comment by emiliocamposmartin** [comment]
good question, is it possible or in the TODO list?

**Comment by VBart** [comment]
It's possible since **Angie 1.2.0**. See [`sticky`](https://angie.software/en/http_upstream/#sticky), [`sticky_strict`](https://angie.software/en/http_upstream/#sticky-strict) and [`sticky_secret`](https://angie.software/en/http_upstream/#sticky-secret) directives in the [HTTP upstream module documentation](https://angie.software/en/http_upstream/).
