### ISSUE TITLE
ngx_http_vod_module.so build maybe missing some options

### ISSUE THREAD

**Issue by rongfengliang** [webserver-llc/angie#53]
when I use angie (angie:1.3.1-alpine) docker image,  after add ngx_http_vod_module.so  module and do some tests

console log will print some warn message, like  this , this will cause  video missing sound 
```code
audio_encoder_process_init: failed to get AAC encoder, audio encoding is disabled. recompile libavcodec with libfdk_aac to enable it
```

**Comment by rongfengliang** [comment]
@VBart soo sorry maybe my fault, I  found  this message not cause any problem (seems just print some warning message ?). It caused by my browser disable audio play.

**Comment by telkar** [comment]
Hello,

Thanks for reporting the issue.
We're glad that everything worked for you, but in any case, we started to figure out the issue and we found the following:
This message appears in the VOD module due to the lack of a library that cannot be used due to licensing restrictions and it doesn't prevent video playback.
Anyway, there is a new version of VOD module that contains fixes in this part. And we will try to ship this new version soon.
Thanks again we will close the issue.
